version: '3.8'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    environment:
      - FLASK_SECRET=${FLASK_SECRET}
      - AES_KEY=${AES_KEY}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - UPLOAD_FOLDER=/data/uploads
      - MAX_CONTENT_MB=${MAX_CONTENT_MB}
    volumes:
      - data_uploads:/data/uploads
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  db_data:
  data_uploads:
